services:
  appdaemon:
    image: acockburn/appdaemon:4.4.2
    container_name: appdaemon
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./apps:/conf/apps
      - ./appdaemon.yaml:/conf/appdaemon.yaml
      - ./conf/ai_logs:/conf/ai_logs
      - ./conf/dashboards:/conf/dashboards
      - ./conf/namespaces:/conf/namespaces

    ports:
      - "5050:5050"
